flags = { group_processes = true }

row = [
  { ratio = 3, child = [
    { type = "cpu" },
    { type = "mem" },
    { type = "net" },
  ] },
  { ration = 3, child = [
    { type = "proc", ratio = 1, default = true },
  ] },
]
