[editor]
bufferline = "multiple"
color-modes = true
completion-replace = true
cursorline = true

gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

idle-timeout = 1

line-number = "relative"

mouse = true
rulers = [ 80 ]
scrolloff = 5

true-color = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
rainbow-option = "dim"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
separator = ""
left = ["mode", "selections", "spinner", "file-name", "total-line-numbers" ]
center = [ ]
right = ["diagnostics", "file-encoding", "file-line-ending", "file-type", "position-percentage", "position" ]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"
            
[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection" ] 

[keys.normal.space.u]
f = ":format" # format using LSP formatter
w = ":set whitespace.render all"
W = ":set whitespace.render none"
